-------------------------------------------------------------------------------
--
-- File: PkgDmaPortDmaFifos.vhd
-- Original Project: LabVIEW FPGA
--
-------------------------------------------------------------------------------
-- (c) Copyright National Instruments Corporation
-- All Rights Reserved
-- National Instruments Internal Information
-------------------------------------------------------------------------------
--
-- Purpose: Package describing the DMA port FIFOs generated by LabVIEW FPGA.
--
--   This is a minimal test fixture standing in for the LabVIEW-generated
--   PkgDmaPortDmaFifos.vhd that is copied into the Window netlist folder.
--
-------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;


package PkgDmaPortDmaFifos is

  constant kNumDmaPortDmaFifos : natural := 0;

end package PkgDmaPortDmaFifos;
