"""Compile the Xilinx ModelSim/Questa simulation libraries (unisim, secureip, ...).

This wraps Vivado's ``compile_simlib`` so that HDL simulation can run on any
machine without the NI build tools. The compiled libraries are written to the
folder configured as ``xilinx_sim_lib_folder`` and are later mapped into
``modelsim.ini`` by ``gen-modelsim``.

The compiled libraries are simulator- and platform-specific, so they cannot be
committed to source control and must be built on the machine where the
simulation runs. Compilation is slow, so this command is idempotent: if the
requested libraries already exist it returns immediately unless ``--force`` is
passed.
"""

# Copyright (c) 2025 National Instruments Corporation
#
# SPDX-License-Identifier: MIT
#

import os
import subprocess
import sys

from labview_fpga_hdl_tools import common
from labview_fpga_hdl_tools.command_config import CommandConfiguration
from labview_fpga_hdl_tools.create_modelsim_project import _find_modelsim_executable
from labview_fpga_hdl_tools.reporting import reporter

# Libraries built when nihdlsettings.py does not specify an explicit scope.
_DEFAULT_XILINX_SIM_LIBRARIES = ["unisim", "secureip"]


def _get_libraries(config):
    """Return the list of Xilinx libraries to compile."""
    if config.xilinx_sim_libraries:
        return list(config.xilinx_sim_libraries)
    return list(_DEFAULT_XILINX_SIM_LIBRARIES)


def _get_modelsim_bin_dir(modelsim_tools_folder):
    """Resolve the directory that holds the ModelSim/Questa executables."""
    vlib = _find_modelsim_executable(modelsim_tools_folder, "vlib")
    if not vlib or not os.path.isfile(vlib):
        return None
    return os.path.dirname(vlib)


def _validate_ini(config):
    """Validate the Vivado/ModelSim tool settings needed to run compile_simlib."""
    missing_settings = []
    invalid_paths = []

    if not config.vivado_tools_folder:
        missing_settings.append("VivadoProjectSettings.VivadoToolsFolder")
    else:
        invalid_path = common.validate_vivado_setting(
            config.vivado_tools_folder,
            "VivadoProjectSettings.VivadoToolsFolder",
        )
        if invalid_path:
            invalid_paths.append(invalid_path)

    if not config.modelsim_tools_folder:
        missing_settings.append("ModelSimSettings.ModelSimToolsFolder")
    else:
        bin_dir = _get_modelsim_bin_dir(config.modelsim_tools_folder)
        if not bin_dir:
            invalid_paths.append(
                f"ModelSimSettings.ModelSimToolsFolder - vlib not found under: "
                f"{config.modelsim_tools_folder}"
            )

    error = common.build_settings_error(missing_settings, invalid_paths)
    if error:
        raise ValueError(error)


def _libraries_already_built(out_folder, libraries):
    """Return True when every requested library already exists in out_folder."""
    if not os.path.isdir(out_folder):
        return False
    for lib in libraries:
        if not os.path.isdir(os.path.join(out_folder, lib)):
            return False
    return True


def _generate_compile_simlib_tcl(tcl_path, bin_dir, out_folder, libraries, family, language):
    """Write the TCL script that drives compile_simlib."""
    bin_dir_fwd = common.fix_file_slashes(bin_dir)
    out_folder_fwd = common.fix_file_slashes(out_folder)

    lines = [
        "# Auto-generated by 'nihdl compile-modelsim-lib'. Do not edit.",
        "compile_simlib \\",
        "    -simulator modelsim \\",
        f'    -simulator_exec_path "{bin_dir_fwd}" \\',
        f"    -family {family} \\",
        f"    -language {language} \\",
    ]
    for lib in libraries:
        lines.append(f"    -library {lib} \\")
    lines.append(f'    -directory "{out_folder_fwd}" \\')
    lines.append("    -force")
    lines.append("")
    lines.append('puts "NIHDL_COMPILE_SIMLIB=DONE"')
    lines.append("")

    os.makedirs(os.path.dirname(tcl_path), exist_ok=True)
    with open(tcl_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def _is_progress_line(line):
    """Return True for compile_simlib lines worth showing in non-verbose mode.

    These are the per-library progress messages (which carry a running
    percentage) and any errors or critical warnings, so the user gets live
    feedback without the full Vivado transcript.
    """
    text = line.strip()
    lowered = text.lower()
    if "% complete" in lowered:
        return True
    if lowered.startswith("compiling ") and "library" in lowered:
        return True
    if "done compilation" in lowered:
        return True
    if text.startswith("ERROR") or text.startswith("CRITICAL WARNING"):
        return True
    return False


def _run_compile_simlib(config, tcl_path, out_folder, libraries):
    """Run the generated compile_simlib TCL script in Vivado batch mode."""
    vivado_abs = common.resolve_vivado_executable_abs(config)

    os.makedirs(out_folder, exist_ok=True)
    # Use a distinct name for Vivado's session log/journal. compile_simlib
    # writes its OWN "compile_simlib.log" into the working directory and renames
    # any existing one to ".bak"; if Vivado's session -log used that same name
    # the rename fails because Vivado holds the file open ("being used by
    # another process").
    log_path = os.path.join(out_folder, "vivado_compile_simlib.log")
    journal_path = os.path.join(out_folder, "vivado_compile_simlib.jou")
    for path in [log_path, journal_path]:
        if os.path.exists(path):
            try:
                os.remove(path)
            except OSError as exc:
                raise RuntimeError(
                    f"Could not remove the previous compile log {path!r}: {exc}. "
                    "Another 'compile-modelsim-lib' (or a Vivado process) may still be "
                    "writing to the shared library folder; wait for it to finish and "
                    "try again."
                ) from exc

    # Build the argument list explicitly and run without a shell so paths that
    # contain spaces or shell-significant characters are passed through verbatim.
    command = [
        vivado_abs,
        "-mode",
        "batch",
        "-source",
        tcl_path,
        "-log",
        log_path,
        "-journal",
        journal_path,
    ]

    # Run with the MODELSIM environment variable unset so compile_simlib does
    # not read or modify a global modelsim.ini; it writes a fresh one into the
    # output directory instead.
    env = os.environ.copy()
    env.pop("MODELSIM", None)

    reporter.detail(f"Vivado executable: {vivado_abs}")
    reporter.detail(f"Output directory:  {out_folder}")
    reporter.detail(f"Libraries:         {', '.join(libraries)}")
    reporter.detail(f"Running command:   {' '.join(command)}")
    reporter.success("")
    reporter.success("=" * 78)
    reporter.success("Compiling the Xilinx ModelSim simulation libraries with Vivado.")
    reporter.success("This is a one-time step and CAN TAKE A LONG WHILE (many minutes).")
    reporter.success(f"  Libraries: {', '.join(libraries)}")
    reporter.success(f"  Output:    {out_folder}")
    reporter.success(f"  Progress:  {os.path.join(out_folder, 'compile_simlib.log')}")
    reporter.success("Please leave this running; it will continue automatically when done.")
    reporter.success("=" * 78)
    reporter.success("")

    # Run Vivado as a streaming subprocess so the user sees live progress while
    # compile_simlib works (it can take many minutes). Vivado batch output is
    # noisy, so by default we surface only the per-library progress lines (which
    # include a running percentage) plus any errors/critical warnings; in
    # verbose mode the full transcript is streamed.
    process = subprocess.Popen(
        command,
        cwd=out_folder,
        shell=False,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    if process.stdout:
        for line in process.stdout:
            if reporter.verbose or _is_progress_line(line):
                sys.stdout.write(line)
                sys.stdout.flush()
    process.wait()

    if process.returncode != 0:
        # compile_simlib returns non-zero if ANY library fails, but it also
        # compiles many bundled Xilinx IP/VIP libraries we never use (e.g. the
        # Zynq/Versal processing-system VIPs, which ModelSim PE cannot parse).
        # Only treat the run as failed if a library we actually requested is
        # missing; otherwise warn and continue.
        missing = [lib for lib in libraries if not os.path.isdir(os.path.join(out_folder, lib))]
        if missing:
            raise RuntimeError(
                "Vivado compile_simlib failed and the requested libraries were not "
                f"produced: {', '.join(missing)} (exit code {process.returncode}). "
                f"See log for details: {log_path}"
            )
        reporter.warn(
            "compile_simlib reported errors in some bundled Xilinx libraries that "
            "are not required for this simulation; the requested libraries "
            f"({', '.join(libraries)}) were built successfully. "
            f"See {log_path} if you need the details."
        )
        return

    if not _libraries_already_built(out_folder, libraries):
        missing = [lib for lib in libraries if not os.path.isdir(os.path.join(out_folder, lib))]
        raise RuntimeError(
            "compile_simlib completed but the following libraries were not produced: "
            f"{', '.join(missing)}. See log for details: {log_path}"
        )


def compile_modelsim_lib(config=None, force=False):
    """Compile the Xilinx ModelSim simulation libraries.

    Args:
        config (CommandConfiguration | None): Configuration object.
        force (bool): Recompile even if the libraries already exist.

    Returns:
        int: 0 for success, 1 for error.
    """
    if config is None:
        config = CommandConfiguration()

    out_folder = config.xilinx_sim_lib_folder
    if not out_folder:
        reporter.error(
            "Error: ModelSimSettings.XilinxSimLibFolder is not configured.\n"
            "Set it in nihdlsettings.py with config.set_xilinx_sim_lib_folder(...)."
        )
        return 1

    libraries = _get_libraries(config)

    # Cheap fast-path: if the libraries are already built we are done and do not
    # even need Vivado/ModelSim resolved. This makes the call safe to run on
    # every gen-modelsim once the libraries have been compiled once.
    if not force and _libraries_already_built(out_folder, libraries):
        reporter.detail(
            f"Xilinx simulation libraries already present in {out_folder} "
            f"({', '.join(libraries)}); skipping compile."
        )
        return 0

    try:
        _validate_ini(config)
    except Exception as e:
        reporter.error(f"Error: {e}")
        return 1

    bin_dir = _get_modelsim_bin_dir(config.modelsim_tools_folder)
    if not bin_dir:
        reporter.error(
            "Error: could not resolve ModelSim executables from " f"{config.modelsim_tools_folder}"
        )
        return 1

    tcl_path = os.path.join(out_folder, "objects", "TCL", "CompileSimLib.tcl")

    family = config.xilinx_sim_family or "all"
    language = config.xilinx_sim_language or "all"

    try:
        _generate_compile_simlib_tcl(tcl_path, bin_dir, out_folder, libraries, family, language)
        _run_compile_simlib(config, tcl_path, out_folder, libraries)
    except Exception as e:
        reporter.error(f"Error: {e}")
        return 1

    reporter.success(
        f"Compiled Xilinx simulation libraries ({', '.join(libraries)}) into {out_folder}."
    )
    return 0
