"""Generated VHDL file generation.

Renders the project's generated VHDL sources from Mako templates. This is the
single batch used by the Vivado (synthesis) and ModelSim (simulation) flows as
well as LabVIEW FPGA target-plugin generation, so the window VHDL, the
PkgNiHdlSettings package, the Board IO signal-assignments example, and any
future generated design sources are all produced together and stay consistent.

This logic lives in its own module (rather than alongside target-plugin
generation) because it is also used by workflows that are not about generating a
LabVIEW FPGA target plugin, such as the standalone ``gen-hdl`` command and the
Vivado/ModelSim project flows.
"""

# Copyright (c) 2025 National Instruments Corporation
#
# SPDX-License-Identifier: MIT
#


import csv  # For reading signal definitions from CSV
import os  # For file and directory operations

from mako.template import Template  # For template-based file generation  # type: ignore

from labview_fpga_hdl_tools import common  # For shared utilities across tools
from labview_fpga_hdl_tools.command_config import CommandConfiguration
from labview_fpga_hdl_tools.reporting import reporter


def _ensure_text(value):
    """Return template output as a text string."""
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return value


def _map_datatype_to_vhdl(data_type):
    """Map CSV data type to VHDL data type."""
    if data_type == "Boolean":
        return "std_logic"

    elif data_type.startswith(("U", "I")):
        # Handle U8, U16, U32, U64, I8, I16, I32, I64. Degrade gracefully to a
        # sentinel (like the FXP/Array branches) instead of crashing the whole
        # flow when the CSV holds a malformed U*/I* data type.
        try:
            bit_width = int(data_type[1:])
        except ValueError:
            return "INVALID_DATA_TYPE"
        return f"std_logic_vector({bit_width - 1} downto 0)"

    elif data_type.startswith("FXP"):
        # Handle FXP type with format: FXP(word_length,int_word_length,Signed/Unsigned)
        try:
            params = data_type.split("(")[1].split(")")[0].split(",")
            word_length = int(params[0])
            return f"std_logic_vector({word_length - 1} downto 0)"
        except (ValueError, IndexError):  # Specify the exceptions you're catching
            return "INVALID_FXP_DATA_TYPE"  # Default if parsing fails

    elif data_type.startswith("Array"):
        # Handle Array type with format: Array<ElementType>[Size]
        try:
            array_size = int(data_type.split("[")[1].split("]")[0])
            element_type = data_type.split("<")[1].split(">")[0]

            # Determine element width based on the type
            if element_type == "Boolean":
                element_width = 1
            elif element_type.startswith(("U", "I")):
                element_width = int(element_type[1:])
            else:
                element_width = 32

            total_width = array_size * element_width
            return f"std_logic_vector({total_width - 1} downto 0)"
        except Exception as e:
            reporter.error(f"Error parsing array type: {data_type}, error: {e}")
            return "INVALID_ARRAY_DATA_TYPE"

    else:
        return "INVALID_DATA_TYPE"  # Default type


def _get_board_io_signals(csv_path):
    """Read Board IO signals from CSV file.

    Reads signal definitions from the CSV and returns a list of signal dictionaries.
    Each dictionary contains properties of a signal such as LV name, HDL name,
    direction, data type, etc.

    Args:
        csv_path (str): Path to the CSV containing signal definitions
    Returns:
        list: List of dictionaries representing Board IO signals
    """
    # Read signals from CSV
    signals = []
    with open(csv_path, "r", newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row["SignalType"].lower() == "clock" and row["Direction"] == "output":
                # Skip output clocks (clocks generated by the FPGA going to the CLIP).
                # These are not driven from TheWindow and are connected manually when
                # the CLIP HDL is instantiated in the top level HDL design.
                continue

            signals.append(
                {
                    "name": row["HDLName"],
                    "direction": "in" if row["Direction"] == "input" else "out",
                    "type": _map_datatype_to_vhdl(row["DataType"]),
                    "lv_name": row["LVName"],
                }
            )
    return signals


def _generate_board_io_signal_assignments_example(csv_path, output_path):
    """Generate Board IO signal assignments example from CSV file.

    Creates a VHDL file containing signal assignments for all Board IO signals.
    Each signal is assigned to itself (e.g., signala <= signala) which can be
    used as a template for connecting signals in HDL designs.

    Args:
        csv_path (str): Path to the CSV containing signal definitions
        output_path (str): Path where the signal assignments file will be written

    Raises:
        RuntimeError: If an error occurs during example generation
    """
    try:
        signals = _get_board_io_signals(csv_path)

        # Generate signal assignments
        assignments = []
        for signal in signals:
            signal_name = signal["name"]
            assignments.append(f"{signal_name} <= {signal_name};")

        # Write to output file
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(assignments))

        reporter.detail(f"Generated Board IO signal assignments: {output_path}")

    except Exception as e:
        raise RuntimeError(f"Failed to generate Board IO signal assignments: {e}") from e


def _get_num_fixed_logic_dma_streams(target_family):
    """Return the number of DMA streams consumed by the fixed (non-user) logic.

    The platform's fixed logic permanently uses a number of DMA streams at the
    top of the channel range. These are reserved and excluded from both the DMA
    channels available to user HDL FIFOs and the channels the LabVIEW FPGA
    diagram may use. This count is the base of
    ``num_reserved_dma_stream_channel_ids`` in the generated target XML and feeds
    ``kNumFixedLogicDmaStreams`` in the generated PkgNiHdlSettings VHDL package.

    This is currently a single per-target-family constant. In the future it can
    be expanded to vary by ``set_target_family`` or ``set_base_target`` (for
    example, a per-base-target lookup) if a family or board ever uses a
    different number of fixed-logic DMA streams.

    Args:
        target_family (str): Target family, from ``set_target_family``.

    Returns:
        int: Number of DMA streams used by the fixed logic.

    Raises:
        ValueError: If the target family has no defined value. New target
            families must add a case below so the correct value is used.
    """
    if target_family == "FlexRIO":
        return 4

    raise ValueError(
        f"Number of fixed-logic DMA streams is not defined for target family "
        f"'{target_family}'. Add a case for this family in "
        f"_get_num_fixed_logic_dma_streams (keyed on set_target_family / "
        f"set_base_target)."
    )


def _build_generated_vhdl_context(config):
    """Build the superset Mako render context for generated VHDL templates.

    Every generated VHDL template is rendered with the same context. Mako
    ignores keys a given template does not reference, so window templates pick
    up ``custom_signals``/IO flags while the settings package picks up
    ``max_hdl_reg_offset``/``num_hdl_fifos``.

    Args:
        config: CommandConfiguration.

    Returns:
        dict: kwargs passed to ``Template.render``.
    """
    signals = []
    if config.custom_io_csv:
        signals = _get_board_io_signals(config.custom_io_csv)

    return {
        "custom_signals": signals,
        "include_board_io": config.include_board_io_on_lv_window,
        "include_custom_io": config.include_custom_io_on_lv_window,
        "max_hdl_reg_offset": (
            config.max_hdl_reg_offset if config.max_hdl_reg_offset is not None else 0
        ),
        "num_hdl_fifos": config.num_hdl_fifos if config.num_hdl_fifos is not None else 0,
        "num_fixed_logic_dma_streams": _get_num_fixed_logic_dma_streams(config.target_family),
    }


def _render_generated_vhdl(template_paths, output_folder, context):
    """Render generated VHDL Mako templates into an output folder.

    Args:
        template_paths (list): Absolute paths to ``.vhd.mako`` templates.
        output_folder (str): Folder where the generated VHDL files are written.
        context (dict): kwargs passed to ``Template.render``.

    Raises:
        RuntimeError: If an error occurs during VHDL generation.
    """
    try:
        os.makedirs(output_folder, exist_ok=True)

        for template_path in template_paths:
            template_basename = os.path.basename(template_path)

            output_filename = (
                template_basename[:-5] if template_basename.endswith(".mako") else template_basename
            )
            output_path = os.path.join(output_folder, output_filename)

            reporter.detail(f"Processing template: {template_path} -> {output_path}")

            with open(template_path, "r", encoding="utf-8") as f:
                template = Template(f.read())

            output_text = template.render(**context)

            with open(output_path, "w", encoding="utf-8") as f:
                f.write(_ensure_text(output_text))

            reporter.detail(f"Generated VHDL file: {output_path}")

    except Exception as e:
        raise RuntimeError(f"Failed to generate VHDL from template: {e}") from e


def _validate_generated_vhdl_settings(config):
    """Validate the settings required to render the generated VHDL files.

    Args:
        config: Configuration object containing settings from INI file.

    Returns:
        tuple: ``(missing_settings, invalid_paths)`` lists describing any
        problems found. Both empty means the VHDL-generation settings are valid.
    """
    missing_settings = common.collect_missing_settings(
        config,
        [("generated_vhdl_output_folder", "LVFPGATargetSettings.GeneratedVhdlOutputFolder")],
    )
    invalid_paths = []

    # Validate input CSV if custom IO is included
    if config.include_custom_io_on_lv_window and not config.custom_io_csv:
        missing_settings.append("LVFPGATargetSettings.LVTargetBoardIO")

    # Validate generated VHDL template paths
    if not config.generated_vhdl_templates:
        missing_settings.append("LVFPGATargetSettings.GeneratedVhdlTemplates")
    else:
        for i, template_path in enumerate(config.generated_vhdl_templates):
            invalid_path = common.validate_path(
                template_path, f"LVFPGATargetSettings.GeneratedVhdlTemplates[{i}]", "file"
            )
            if invalid_path:
                invalid_paths.append(invalid_path)

    return missing_settings, invalid_paths


def gen_generated_vhdl(config=None):
    """Generate all configured VHDL files from Mako templates.

    Standalone entry point that renders every template registered with
    ``add_generated_vhdl_template`` into the generated VHDL output folder. This
    is the single batch used by both the Vivado (synthesis) and ModelSim
    (simulation) flows, so window VHDL, the PkgNiHdlSettings package, and any
    future generated design sources are all produced together and stay
    consistent between synthesis and simulation.

    Returns:
        int: 0 if successful, 1 if errors occurred
    """
    # Load configuration
    if config is None:
        config = CommandConfiguration()

    if not config.generated_vhdl_templates:
        # Nothing to generate; not an error.
        return 0

    # Validate that required settings for generation are present
    missing_settings, invalid_paths = _validate_generated_vhdl_settings(config)
    error = common.build_settings_error(missing_settings, invalid_paths)
    if error:
        reporter.error(f"Error: {error}")
        return 1

    context = _build_generated_vhdl_context(config)
    try:
        _render_generated_vhdl(
            config.generated_vhdl_templates,
            config.generated_vhdl_output_folder,
            context,
        )
    except Exception as e:
        reporter.error(f"Error: {e}")
        return 1

    reporter.success("Generated VHDL generation complete.")
    return 0
