"""Get a LabVIEW Window netlist from the exported Vivado project."""

# Copyright (c) 2025 National Instruments Corporation
#
# SPDX-License-Identifier: MIT
#


import os
import shutil

from . import common
from .reporting import reporter

# Generated flat wrapper file produced by the GetWindowNetlist TCL script.
_WINDOW_FLAT_WRAPPER_FILE = "TheLvWindowFlatWrapper.v"


def _get_window_netlist(config):
    """Gets the Window netlist from the Vivado Project as well as other HDL Files."""
    get_netlist_tcl_path = os.path.join(
        os.getcwd(), config.vivado_tcl_scripts_folder, "GetWindowNetlist.tcl"
    )
    reporter.detail(f"Using TCL script at: {get_netlist_tcl_path}")
    current_dir = os.getcwd()

    # Extract project directory and name from the XPR path
    vivado_project_path = os.path.dirname(config.lv_window_vivado_project_export_xpr)
    project_name = os.path.splitext(os.path.basename(config.lv_window_vivado_project_export_xpr))[0]

    reporter.detail(f"Vivado project path: {vivado_project_path}")
    reporter.detail(f"Vivado project name: {project_name}")

    os.chdir(vivado_project_path)

    # Determine Vivado executable from either direct executable path or tools dir.
    vivado_executable = common.get_vivado_executable(config.vivado_tools_folder)
    if not vivado_executable:
        os.chdir(current_dir)
        raise ValueError("Unable to resolve Vivado executable from configuration")

    vivado_abs = os.path.abspath(vivado_executable)
    if not config.skip_vivado and not os.path.exists(vivado_abs):
        os.chdir(current_dir)
        raise FileNotFoundError(
            f"Vivado executable not found at: {vivado_abs}\n"
            f"Please check your --vivado argument or VivadoToolsFolder setting in nihdlsettings.py"
        )

    source_file = os.path.join(vivado_project_path, _WINDOW_FLAT_WRAPPER_FILE)
    destination_folder = config.lv_window_netlist_output_folder

    # Create destination directory if it doesn't exist
    os.makedirs(destination_folder, exist_ok=True)

    # In skip_vivado mode, skip running Vivado
    if config.skip_vivado:
        reporter.detail("SKIP VIVADO: Skipping Vivado execution")

        # Create a mock Verilog netlist file if it doesn't exist
        if not os.path.exists(source_file):
            with open(source_file, "w") as f:
                f.write("// Mock Verilog netlist file created for testing\n")
            reporter.detail(f"Created mock Verilog netlist file for testing: {source_file}")
    else:
        reporter.detail(f"Current working directory: {os.getcwd()}")
        common.run_command(
            f'"{vivado_abs}" {project_name}.xpr -mode batch -source {get_netlist_tcl_path}',
            cwd=os.getcwd(),
            capture_output=False,
        )

        # Check for success marker in vivado.log file
        vivado_log_path = os.path.join(os.getcwd(), "vivado.log")
        if not os.path.exists(vivado_log_path):
            os.chdir(current_dir)
            raise RuntimeError("Vivado log file not found. TCL script execution may have failed.")

        # Read the log file and check for success marker
        try:
            with open(vivado_log_path, "r", encoding="utf-8", errors="replace") as log_file:
                log_content = log_file.read()
                # This GET_WINDOW=FAILED constant is set in the GetWindowNetlist.tcl file
                # We have not found a better way to surface an error from Vivado executing a
                # TCL script up to Python
                if "GET_WINDOW=FAILED" in log_content:
                    os.chdir(current_dir)
                    raise RuntimeError("Window netlist extraction failed.")
        except Exception as e:
            os.chdir(current_dir)
            raise RuntimeError(f"Errors found in Vivado log file: {str(e)}")

        # Check if the expected output file was generated
        if not os.path.exists(source_file):
            os.chdir(current_dir)
            raise RuntimeError(
                f"Vivado TCL script execution failed: Expected output file {source_file} was not generated."
            )

    destination_file = os.path.join(destination_folder, _WINDOW_FLAT_WRAPPER_FILE)

    try:
        if os.path.exists(source_file):
            shutil.copy(source_file, destination_file)
            reporter.detail(f"Copied {source_file} to {destination_file}")
        else:
            os.chdir(current_dir)
            raise FileNotFoundError(f"Source file {source_file} not found")
    except Exception as e:
        os.chdir(current_dir)
        raise RuntimeError(f"Error copying file: {str(e)}")

    os.chdir(current_dir)


def _copy_lv_generated_files(config):
    """Copy files that are generated by LV into TheWindow folder for use in the HDL vivado flow."""
    # Extract the parent directory path from the XPR path
    # The NIProtectedFiles folder is typically at the same level as VivadoProject
    project_export_base = os.path.dirname(
        os.path.dirname(config.lv_window_vivado_project_export_xpr)
    )
    protected_files_folder = os.path.join(project_export_base, "NIProtectedFiles")

    # This list is hardcoded for now
    #
    # As we expand to future target support, we may need to make the list of LV FPGA generated
    # files to copy more dynamic based on the target
    files_to_copy = [
        "CodeGenerationResults.lvtxt",
        "PkgLvFpgaConst.vhd",
        "PkgCommIntConfiguration.vhd",
        "PkgDmaPortCommIfcRegs.vhd",
        "PkgDmaPortDmaFifos.vhd",
    ]

    for file_name in files_to_copy:
        source_file = os.path.join(protected_files_folder, file_name)
        destination_file = os.path.join(config.lv_window_netlist_output_folder, file_name)

        try:
            if os.path.exists(source_file):
                shutil.copy(source_file, destination_file)
                reporter.detail(f"Copied {source_file} to {destination_file}")
            else:
                reporter.error(f"Error: Source file {source_file} not found")
        except Exception as e:
            reporter.error(f"Error copying file: {str(e)}")


def _extract_lv_window_constraints(config):
    """Extract LabVIEW FPGA constraints from the main constraints.xdc file.

    This function finds the constraints section marked with BEGIN_LV_FPGA_CONSTRAINTS and
    END_LV_FPGA_CONSTRAINTS in the constraints.xdc file, and creates a separate file
    containing just those constraints in the Window folder, excluding the marker lines.

    Args:
        config (CommandConfiguration): Configuration settings object
    """
    # Extract the parent directory path from the XPR path
    # The NIProtectedFiles folder is typically at the same level as VivadoProject
    project_export_base = os.path.dirname(
        os.path.dirname(config.lv_window_vivado_project_export_xpr)
    )
    protected_files_folder = os.path.join(project_export_base, "NIProtectedFiles")

    source_file = os.path.join(protected_files_folder, "constraints.xdc")
    destination_folder = config.lv_window_netlist_output_folder
    destination_file = os.path.join(destination_folder, "TheWindowConstraints.xdc")

    # Make sure destination folder exists
    os.makedirs(destination_folder, exist_ok=True)

    # Extract constraints between markers
    try:
        if os.path.exists(source_file):
            with open(source_file, "r", encoding="utf-8") as f_in:
                lines = f_in.readlines()

            # Find the marker lines
            start_idx = None
            end_idx = None

            for i, line in enumerate(lines):
                if "# BEGIN_LV_FPGA_CONSTRAINTS" in line:
                    start_idx = i
                if "# END_LV_FPGA_CONSTRAINTS" in line:
                    end_idx = i
                    break

            # Check if markers were found
            if start_idx is None or end_idx is None:
                reporter.warn("Warning: Could not find constraint markers in constraints.xdc")
                return

            # Extract the constraints EXCLUDING the marker lines
            lv_constraints = lines[start_idx + 1 : end_idx]

            # Write the constraints to the destination file
            with open(destination_file, "w", encoding="utf-8") as f_out:
                f_out.writelines(lv_constraints)

            reporter.success(f"Successfully extracted LV FPGA constraints to {destination_file}")
        else:
            reporter.error(f"Error: Source file {source_file} not found")
    except Exception as e:
        reporter.error(f"Error extracting constraints: {str(e)}")


def _validate_ini(config):
    """Validate that all required configuration settings are present.

    This function checks that all settings required for getting window netlist
    are present in the configuration object and validates that paths exist.

    Args:
        config: Configuration object containing settings from INI file

    Raises:
        ValueError: If any required settings are missing or paths are invalid
    """
    missing_settings = []
    invalid_paths = []

    # Check required paths for window netlist generation
    if not config.lv_window_vivado_project_export_xpr:
        missing_settings.append("LVWindowNetlistSettings.LVWindowVivadoProjectExportXPR")
    else:
        # Validate that the XPR file exists
        invalid_path = common.validate_path(
            config.lv_window_vivado_project_export_xpr,
            "LVWindowNetlistSettings.LVWindowVivadoProjectExportXPR",
            "file",
        )
        if invalid_path:
            invalid_paths.append(invalid_path)
        if not config.skip_vivado:
            # Check that the project folder path length does not exceed 80 characters
            # OK to skip this check in skip_vivado mode because we are not running Vivado
            vivado_project_path = os.path.dirname(config.lv_window_vivado_project_export_xpr)
            if len(vivado_project_path) > 80:
                raise ValueError(
                    f"Error: Vivado project path exceeds 80 characters ({len(vivado_project_path)} chars).\n"
                    f"Path: {vivado_project_path}\n"
                    f"Vivado has issues with long paths. Please use a shorter path for your project."
                )

    if not config.lv_window_netlist_output_folder:
        missing_settings.append("LVWindowNetlistSettings.LVWindowFolder")

    # Check for Vivado tools path
    if not config.vivado_tools_folder:
        missing_settings.append("VivadoProjectSettings.VivadoToolsFolder")
    else:
        # Validate Vivado setting as either tools dir or executable path.
        invalid_path = common.validate_vivado_setting(
            config.vivado_tools_folder,
            "VivadoProjectSettings.VivadoToolsFolder",
        )
        if invalid_path:
            invalid_paths.append(invalid_path)

    # Construct error message using common utility functions
    error_msg = common.get_missing_settings_error(missing_settings)
    error_msg += common.get_invalid_paths_error(invalid_paths)

    # If any issues found, raise an error with the helpful message
    if missing_settings or invalid_paths:
        error_msg += "\nPlease update your configuration file and try again."
        raise ValueError(error_msg)


def get_window(config=None):
    """Main entry point for the script."""
    # Load configuration
    if config is None:
        config = common.CommandConfiguration()

    # Validate that all required settings are present
    try:
        _validate_ini(config)
    except Exception as e:
        reporter.error(f"Error: {e}")
        return 1

    _get_window_netlist(config)
    _copy_lv_generated_files(config)
    _extract_lv_window_constraints(config)

    reporter.success("Window netlist extraction completed successfully.")

    reporter.success("\n" + "=" * 80)
    reporter.success("NOTICE: If you have already created a Vivado project, you must run")
    reporter.success(
        '         "nihdl create-project --update" to pull in the latest Window netlist files.'
    )
    reporter.success("=" * 80)

    return 0
