name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check_nitypes:
    name: Check nitypes
    uses: ./.github/workflows/check_nitypes.yml
  run_tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yml
    needs: []